name: patrimonio
description: "Aplicativo movel para gerenciar patrimonio do coltec"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_database: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/