// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQCl5BHVpmeIBnpM3YdNBYHKszQG035M',
    appId: '1:55236335981:web:bf082498afa98c4422a264',
    messagingSenderId: '55236335981',
    projectId: 'patrimonio-9b669',
    authDomain: 'patrimonio-9b669.firebaseapp.com',
    storageBucket: 'patrimonio-9b669.firebasestorage.app',
    measurementId: 'G-M8HPHX4VD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6L_WAiTi7LaKH_XQ9gZF8wuHLSNBzIjQ',
    appId: '1:55236335981:android:282f2f071a6e05df22a264',
    messagingSenderId: '55236335981',
    projectId: 'patrimonio-9b669',
    storageBucket: 'patrimonio-9b669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgPEAmKdYioD52MDB7nW3q1Rz2Nv15wvw',
    appId: '1:55236335981:ios:4005d6ef1f9bf7f322a264',
    messagingSenderId: '55236335981',
    projectId: 'patrimonio-9b669',
    storageBucket: 'patrimonio-9b669.firebasestorage.app',
    iosBundleId: 'com.example.patrimonio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgPEAmKdYioD52MDB7nW3q1Rz2Nv15wvw',
    appId: '1:55236335981:ios:4005d6ef1f9bf7f322a264',
    messagingSenderId: '55236335981',
    projectId: 'patrimonio-9b669',
    storageBucket: 'patrimonio-9b669.firebasestorage.app',
    iosBundleId: 'com.example.patrimonio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdQCl5BHVpmeIBnpM3YdNBYHKszQG035M',
    appId: '1:55236335981:web:1297f523b66e1ee022a264',
    messagingSenderId: '55236335981',
    projectId: 'patrimonio-9b669',
    authDomain: 'patrimonio-9b669.firebaseapp.com',
    storageBucket: 'patrimonio-9b669.firebasestorage.app',
    measurementId: 'G-HEB8MZPGBK',
  );
}
